#!/bin/sh -e

readonly AWK_SCRIPT='
BEGIN {
    FS="<|><!\\[CDATA\\[|]]></|>"
}

$2 == "chanteur" {
    c = 1;
    print $3
}

$2 == "chanson" && c {
    c = 0;
    print $3
}
'

main() {
    awk "$AWK_SCRIPT" | sed 'N; s/\n/ - /'
}

main "$@"
