#!/bin/sh -e

# Radio anchor xpath
RAX='//a[@rel="open_player"][@class="webradio"]'

# XML base url
XBU='http://generations.fr/winradio/prog'

# Stream input value xpath expression
SIX='string(//input[@id="flux"]/@value)'

curl -s http://generations.fr/ \
    | xmllint --html --xpath "$RAX/@href | $RAX/text()" - 2> /dev/null \
    | sed 's/ href="/\n/g' \
    | sed 's/"/\n/; 1d; $a\' \
    | awk 'NR % 2 {print "'"$XBU"'" (NR + 1) / 2 ".xml"} 1' \
    | xargs -d'\n' -L3 sh -c \
        'echo "$3" && curl -s "$2" | xmllint --html --xpath "$0" - 2> /dev/null && echo && echo "$1"' \
        "$SIX"
