#!/bin/sh -e

if ! [ "${1:+1}" ]; then
    in='/dev/stdin'
    file='-'
else
    in='/dev/null'
    file="$1"
fi

cat "$in" \
    | xmllint --format "$file" \
    | awk -F'<|><!\\[CDATA\\[|]]></|>' '$2 == "chanteur" {c = 1; print $3} $2 == "chanson" && c {c = 0; print $3}' \
    | sed 'N; s/\n/ - /'
